### PR TITLE
Database Schema

### PR DESCRIPTION
**Pull request by gandharvsuri**
Database Schema setup.

### CODE REVIEW

**Comment by Anirudh-C** [comment]
Can we do this:
- Write a simple Dockerfile that performs all the specified in README.md (can use build arguments if needed for the credentials). I feel that will be easier to use in the pipeline.
- Running the container should check if the database that has been mounted (via a bind mount for example) contains the required tables. If not then run schema.sql else do nothing.
- Additionally we have an ENTRYPOINT to our container that just takes SQL queries as input.

**Comment by gandharvsuri** [comment]
@Anirudh-C  
> * Write a simple Dockerfile that performs all the specified commands in README.md (can use build arguments if needed for the credentials). I feel that will be easier to use in the pipeline.

Then for the Dockerfile we can just build the MySQL image and move the SQL script to the working directory rest of the steps of login into MySQL need to be done explicitly right? Cause we need to have the container running for that.

**Comment by Anirudh-C** [comment]
No I don't think so. Here's what I was thinking (I'm not sure about databases so correct me wherever I go wrong): our mysql image acts as the SQL server. Meaning we make our SQL queries to our container which processes them and updates/reads from a database which is stored on some physical machine and is mounted to the container.

The build process I think could be something like this:
1. Start with the mysql base image
2. Copy the schema.sql into the working directory
3. Run MySQL login
4. Run the schema.sql if the database doesn't have the required tables.
Also, the entrypoint to our container will be mysql. So if we execute `docker run -it -v fpl.db:/fpl.db fpl-db add.sql`, the container will just run the script add.sql and update the database file fpl.db

**Comment by gandharvsuri** [comment]
> 3. Run MySQL login

That's what, I don't think we can log in to MySQL during the build stage. The container needs to be running to login into MySQL. 
Although I'm trying to run a shell script using CMD command that will log in to MySQL and run the SQL script.

**Comment by Anirudh-C** [comment]
Cool okay! That seems fine. Also is it possible to create the tables only if they don't already exist? I assumed it would be possible but I don't know how to do it

**Comment by gandharvsuri** [comment]
Yup, instead of tables I'm keeping a check on the database, if the database exists I'm deleting it and creating a new one every time we run this initial script. 
For the update tables script, we'll keep a check on the tables if they exist or not.

**Comment by Anirudh-C** [comment]
That's inefficient. If say we've already populated the DB then if we restart the DB container it will delete all the data right? We only need to change the DB if the schema changes. Let's do the table check everywhere. If the schema changes we will be able to see that some tables in the schema are not there in the DB and add those.

**Comment by gandharvsuri** [comment]
Restarting the container isn't the desired situation, so it's better to create the DB again than to keep a check on the existence of the tables. Once we start the container we expect it to be running, and we'll only be performing the update-DB script periodically. Also if the container is down for some time, we'll be anyways expected to rerun the update-DB script to avoid inconsistent and old data, so won't affect the efficiency that much.

**Comment by Anirudh-C** [comment]
I think it's just safer to check for existence of the table than deleting the database every time and it is not an incorrect solution so I don't see why we shouldn't do it. And this reduces the work we have to do as well. You write that logic once and it can be reused in the DB update script as well.

Also another point to note is that it might not be feasible to pull all the data once again from the FPL API. They will have some fixed limit on the number of queries we can make. In fact Arjun ran into this issue as well. So once we instantiate the database we let it be. We don't keep deleting it and making it again. That seems like poor design.

**Comment by gandharvsuri** [comment]
I don't think it's a poor design. For development, since there is a limit on the calls to the FPL API we can keep a check on the tables, but logically keeping a check on the DB if we're building the container makes more sense, cause there could be inconsistency in the stored data and actual data.

**Pull request closed without merging**
